### PR TITLE
[TIMOB-25573] Javascript minification produces wrong code

### PR DESCRIPTION
**Pull request by feons**
https://jira.appcelerator.org/browse/TIMOB-25573

### CODE REVIEW

**Comment by hansemannn** [comment]
LGTM! I looked at other projects like RN and they also had massive issues with babel's aggressive minification. Maybe we can confirm that we catch everything by looking at their ones as well? Also, we need a master and 7_0_X PR for appcelerator/titanium_mobile until tomorrow to get this into 7.0.1. Thx!

**Comment by feons** [comment]
@hansemannn, looking at the node-titanium-sdk version specified, https://github.com/appcelerator/titanium_mobile/blob/master/package.json#L42, the newer version of the module will be included once the publish is published. Do we still need PR appcelerator/titanium_mobile to trigger a build?

**Comment by hansemannn** [comment]
Not sure. @sgtcoolguy Best practice?

**Comment by sgtcoolguy** [comment]
It's good practice to PR the SDK as well. It's supposed to use the exact versions specified in package-lock.json. NPM sometimes does and sometimes doesn't, but that's their issue(s).

In any case, when you want to update a dependency you should explicitly run something like `npm install node-titanium-sdk@^0.4.6` in the SDK and it'll pull the new version and update package.json and package-lock.json for you.

**Pull request merged**
